import type { Metadata } from "next";
import "../globals.css";
import GlobalModal from "@/components/modal-views/container";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  console.log("local form main", locale);

  const localeLang = await getLocale();
  return (
    <html lang={locale} dir={localeLang === "ar" ? "rtl" : "ltr"}>
      <body>
        <GlobalModal />
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
