import type { Metadata } from "next";
import "../globals.css";

import { getLocale, getMessages } from "next-intl/server";

import ClientProvider from "./ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const localeLang = await getLocale();

  return (
    <ClientProvider messages={messages} localeLang={localeLang}>
      {children}
    </ClientProvider>
  );
}